export const teamInfo = [
{
    name: 'Nikolay Maloshenko',
    github: 'https://github.com/Nikolay96UA',
    linkedin: '',
    role: 'Team-leader',
    telegram: '',
    img: 'https://avatars.githubusercontent.com/u/115625550?v=4',
  },
  {
    name: 'Vadim Borovec',
    github: 'https://github.com/VadBorovec',
    linkedin: 'https://www.linkedin.com/in/vadymborovets/',
    role: 'Scrum-master/Developer',
    telegram: '',
    img: 'https://avatars.githubusercontent.com/u/112804701?v=4',
  },
  {
    name: 'Dmytro Miroshnychenko',
    github: 'https://github.com/DmitriyMiroshnychenko',
    linkedin: 'https://www.linkedin.com/in/дмитрий-мирошниченко-5b7b13116',
    role: 'Developer',
    telegram: 'https://t.me/FdevSt',
    img: 'https://avatars.githubusercontent.com/u/88747340?v=4',
  },

  {
    name: 'Yuri Yatsenko',
    github: 'https://github.com/YuriiYatsenko',
    linkedin: '',
    role: 'Developer',
    telegram: '',
    img: 'https://avatars.githubusercontent.com/u/115614039?v=4',
  },
  {
    name: 'Vitaliu Tokman',
    github: 'https://github.com/Vital3414',
    linkedin: '',
    role: 'Developer',
    telegram: '',
    img: 'https://avatars.githubusercontent.com/u/112972483?v=4',
  },
  {
    name: 'Artur Salakhutdinov',
    github: 'https://github.com/ArturS2307',
    linkedin: '',
    role: 'Developer',
    telegram: '',
    img: 'https://avatars.githubusercontent.com/u/111919857?v=4',
  },
  {
    name: 'Denis Prohorchuk',
    github: '',
    linkedin: '',
    role: 'Developer',
    img: 'https://ca.slack-edge.com/T04HC3SKKV3-U04KSEJ7NG2-3b8dbc030740-512',
  },
  {
    name: 'Y Kosytsia',
    github: '',
    linkedin: '',
    role: 'Developer',
    img: 'https://ca.slack-edge.com/T04HC3SKKV3-U0561HM0FA7-gb7ba503209d-512',
  },
  {
    name: 'Konstyantyn Umanec',
    github: '',
    linkedin: '',
    role: 'Developer',
    telegram: '',
    img: 'https://ca.slack-edge.com/T04HC3SKKV3-U04KPJERU8H-g7e0a2fea511-512',
  },
];
